repos:
-   repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i --style=file
        files: \.(cpp|cc|h|hpp)$
        language: system

# -   repo: local
#     hooks:
#       - id: clang-tidy
#         name: clang-tidy
#         entry: clang-tidy --config-file=.clang-tidy
#         files: \.(cpp|cc|h|hpp)$
#         # skip for the moment 
#         exclude: |
#           (?x)^(
#               flagcx/flagcx.cc|
#               flagcx/include/flagcx.h
#           )$
#         language: system
